Define socklen_t as "int" if missing, not "unsigned". (accept(2) et. al. traditionally took "int *" before POSIX invented socklen_t) Use AC_TRY_COMPILE instead of AC_EGREP_HEADER for socklen_t test. Regenerated configure script.

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -15093,29 +15093,56 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-    #include <sys/types.h>
-    #include <sys/socket.h>
-    #if STDC_HEADERS
-    #include <stdlib.h>
-    #include <stddef.h>
-    #endif
+	#include <sys/types.h>
+	#include <sys/socket.h>
 
+int
+main ()
+{
+
+    	socklen_t foo;
+
+  ;
+  return 0;
+}
 _ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  $EGREP "(^|[^a-zA-Z_0-9])socklen_t[^a-zA-Z_0-9]" >/dev/null 2>&1; then
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
   tcl_cv_type_socklen_t=yes
 else
-  tcl_cv_type_socklen_t=no
-fi
-rm -f conftest*
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
+tcl_cv_type_socklen_t=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $tcl_cv_type_socklen_t" >&5
 echo "${ECHO_T}$tcl_cv_type_socklen_t" >&6
 if test $tcl_cv_type_socklen_t = no; then
 
 cat >>confdefs.h <<\_ACEOF
-#define socklen_t unsigned
+#define socklen_t int
 _ACEOF
 
 fi
