win/configure: check whether cpuid-header natively supported for the target architecture (possible fix for [d58e31517203396e])

diff --git a/win/configure b/win/configure
--- a/win/configure
+++ b/win/configure
@@ -4947,6 +4947,80 @@ _ACEOF
 
 fi
 
+# See if the compiler supports cpuid header.
+
+if test "${GCC}" = "yes" ; then
+  echo "$as_me:$LINENO: checking for cpuid-header support in compiler" >&5
+echo $ECHO_N "checking for cpuid-header support in compiler... $ECHO_C" >&6
+if test "${tcl_cv_cpuidhead+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+  #if defined (__clang__) || ((__GNUC__)  && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 8))))
+  #   include <cpuid.h>
+  #endif
+
+int
+main ()
+{
+
+    unsigned int regs;
+    __get_cpuid(0, &regs, &regs, &regs, &regs);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tcl_cv_cpuidhead=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+tcl_cv_cpuidhead=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $tcl_cv_cpuidhead" >&5
+echo "${ECHO_T}$tcl_cv_cpuidhead" >&6
+  if test "$tcl_cv_cpuidhead" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CPUID_H 1
+_ACEOF
+
+  fi
+fi
+
 # See if the <wspiapi.h> header file is present
 
 echo "$as_me:$LINENO: checking for wspiapi.h" >&5
