Merge updates from HEAD.

diff --git a/win/configure b/win/configure
--- a/win/configure
+++ b/win/configure
@@ -1274,7 +1274,7 @@ SHELL=/bin/sh
 TCL_VERSION=8.5
 TCL_MAJOR_VERSION=8
 TCL_MINOR_VERSION=5
-TCL_PATCH_LEVEL="a1"
+TCL_PATCH_LEVEL="a2"
 VER=$TCL_MAJOR_VERSION$TCL_MINOR_VERSION
 
 TCL_DDE_VERSION=1.3
@@ -2865,6 +2865,68 @@ if test "$tcl_cv_findex_enums" = "no"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_NO_FINDEX_ENUMS 1
+_ACEOF
+
+fi
+
+# See if MWMO_ALERTABLE is missing from winuser.h
+# This is known to be a problem with Mingw.
+
+echo "$as_me:$LINENO: checking for MWMO_ALERTABLE in winuser.h" >&5
+echo $ECHO_N "checking for MWMO_ALERTABLE in winuser.h... $ECHO_C" >&6
+if test "${tcl_cv_mwmo_alertable+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#define WIN32_LEAN_AND_MEAN
+#include <windows.h>
+#undef WIN32_LEAN_AND_MEAN
+
+int
+main ()
+{
+
+  int i = MWMO_ALERTABLE;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tcl_cv_mwmo_alertable=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+tcl_cv_mwmo_alertable=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $tcl_cv_mwmo_alertable" >&5
+echo "${ECHO_T}$tcl_cv_mwmo_alertable" >&6
+if test "$tcl_cv_mwmo_alertable" = "no"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NO_MWMO_ALERTABLE 1
 _ACEOF
 
 fi
