That script can be used on the other two platforms too. Excellent!

diff --git a/.github/workflows/linux-build.yml b/.github/workflows/linux-build.yml
--- a/.github/workflows/linux-build.yml
+++ b/.github/workflows/linux-build.yml
@@ -92,7 +92,7 @@ jobs:
       - name: Info
         run: |
           ulimit -a || echo 'get limit failed'
-          echo 'puts exe:\t[info nameofexecutable]\nver:\t[info patchlevel]\t[if {![catch tcl::build-info ret]} {set ret}]\nlib:\t[info library]\nplat:\t[lsort -dictionary -stride 2 [array get tcl_platform]]' | make runtest || echo 'get info failed'
+          make runtest sCRIPT=../.github/workflows/info.tcl || echo 'get info failed'
       - name: Run Tests
         run: |
           make test
